# Generated by Django 4.1.2 on 2022-11-08 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_descricao', models.CharField(max_length=255)),
                ('mod_categoria', models.CharField(choices=[('PROGRAMAÇÃO', 'Programação'), ('BANCO DE DADOS', 'Banco de Dados'), ('IA', 'Machine/Deep Learn'), ('VISUALIZAÇÃO DE DADOS', 'Visualização de Dados'), ('OUTROS', 'Outros')], max_length=50)),
            ],
            options={
                'db_table': 'modulo',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='bootcamp',
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='link_interesse',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='tipo',
            field=models.CharField(choices=[('STREAMING', 'Video Streaming (Youtube)'), ('DOCUMENTOS', 'Documentos PDF'), ('VIDEO', 'Arquivos de Vídeo (mp4)'), ('PROVA', 'Link de Avaliação de Módulo')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='thumb',
            field=models.ImageField(upload_to='thumb_app'),
        ),
        migrations.AlterModelTable(
            name='bootcamp',
            table='bootcamp',
        ),
        migrations.AlterModelTable(
            name='conteudo',
            table='conteudo',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.CreateModel(
            name='Modulo_usu_acomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moa_data_ini', models.DateTimeField(default=django.utils.timezone.now)),
                ('moa_data_fim', models.DateTimeField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_consumidos', to='bootcamp.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_modulos_acomp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modulo_usu_acomp',
            },
        ),
        migrations.CreateModel(
            name='Modulo_Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamps_modulo', to='bootcamp.bootcamp')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='bootcamp.modulo')),
            ],
            options={
                'db_table': 'modulo_bootcamp',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='bootcamps',
            field=models.ManyToManyField(blank=True, through='bootcamp.Modulo_Bootcamp', to='bootcamp.bootcamp'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamps_matricula', to='bootcamp.bootcamp')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_matriculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='Conteudo_usu_acomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_consumidos', to='bootcamp.conteudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acomp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conteudo_usu_acomp',
            },
        ),
        migrations.CreateModel(
            name='Conteudo_Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='bootcamp.conteudo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_conteudo', to='bootcamp.modulo')),
            ],
            options={
                'db_table': 'conteudo_modulo',
            },
        ),
        migrations.AddField(
            model_name='conteudo',
            name='modulos',
            field=models.ManyToManyField(blank=True, through='bootcamp.Conteudo_Modulo', to='bootcamp.modulo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conteudos_vistos',
            field=models.ManyToManyField(blank=True, through='bootcamp.Conteudo_usu_acomp', to='bootcamp.conteudo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulos_vistos',
            field=models.ManyToManyField(blank=True, through='bootcamp.Modulo_usu_acomp', to='bootcamp.modulo'),
        ),
    ]
