# Generated by Django 4.1.2 on 2022-11-09 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_modulo_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Interesse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_nascimento', models.DateTimeField(blank=True, default=None, null=True)),
                ('genero', models.CharField(blank=True, choices=[('HOMEM CIS', 'Homem Cis'), ('MULHER CIS', 'Mulher Cis'), ('HOMEM TRANS', 'Homem Trans'), ('MULHER TRANS', 'Mulher Trans'), ('TRAVESTI', 'Travesti'), ('NAO BINARIO', 'Não Binário'), ('OUTROS', 'Outros'), ('NAO INFORMADO', 'Não quero Informar')], default=None, max_length=150, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('cidade', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lgpd', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('veracidade', models.BooleanField(blank=True, default=False, null=True)),
                ('receber_mensagens', models.BooleanField(blank=True, default=False, null=True)),
                ('aprovado', models.BooleanField(blank=True, default=False, null=True)),
                ('bootcamp_titulo', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
            options={
                'db_table': 'usuario_interesse',
            },
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='categoria',
            field=models.CharField(choices=[('ENGENHARIA DE DADOS', 'Engenharia de Dados'), ('CIÊNCIA DE DADOS', 'Ciência de Dados'), ('VISUALIZAÇÃO DE DADOS', 'Visualização de Dados'), ('OUTROS', 'Outros')], max_length=150),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='titulo',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='tipo',
            field=models.CharField(choices=[('STREAMING', 'Video Streaming (Youtube)'), ('DOCUMENTOS', 'Documentos PDF'), ('VIDEO', 'Arquivos de Vídeo (mp4)'), ('PROVA', 'Link de Avaliação de Módulo')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='conteudo_modulo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conteudo_usu_acomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='mod_categoria',
            field=models.CharField(choices=[('PROGRAMAÇÃO', 'Programação'), ('BANCO DE DADOS', 'Banco de Dados'), ('IA', 'Machine/Deep Learn'), ('VISUALIZAÇÃO DE DADOS', 'Visualização de Dados'), ('OUTROS', 'Outros')], max_length=150),
        ),
        migrations.AlterField(
            model_name='modulo_bootcamp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulo_usu_acomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulo_usu_acomp',
            name='moa_data_fim',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bootcamps_vistos',
            field=models.ManyToManyField(blank=True, to='bootcamp.bootcamp'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
